"""Alter visualizations.id to GENERATED BY DEFAULT AS IDENTITY (Postgres auto-increment)

Revision ID: 2025_06_18_0200
Revises: 2025_06_18_0100
Create Date: 2025-06-18 02:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2025_06_18_0200'
down_revision = '2025_06_18_0100'
branch_labels = None
depends_on = None

def upgrade():
    # Only run for Postgres
    op.execute('ALTER TABLE visualizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')

def downgrade():
    # Downgrade: remove identity (not always reversible, so just drop identity if possible)
    op.execute('ALTER TABLE visualizations ALTER COLUMN id DROP IDENTITY IF EXISTS') 