"""add_validation_error_tracking

Revision ID: 21ba1eb51833
Revises: 2025_06_18_0200
Create Date: 2025-06-19 11:25:30.942113+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21ba1eb51833"
down_revision: Union[str, None] = "2025_06_18_0200"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("visualization_id", sa.Integer(), nullable=True),
        sa.Column("prompt_id", sa.Integer(), nullable=True),
        sa.Column("phase", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("error_type", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("suggestion", sa.Text(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["visualization_id"],
            ["visualizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_validation_errors_created_at"),
        "validation_errors",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_validation_errors_error_type"),
        "validation_errors",
        ["error_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_validation_errors_id"), "validation_errors", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_validation_errors_phase"), "validation_errors", ["phase"], unique=False
    )
    op.create_index(
        op.f("ix_validation_errors_severity"),
        "validation_errors",
        ["severity"],
        unique=False,
    )
    op.alter_column(
        "gold_standard_upload_status",
        "id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "gold_standard_upload_status",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "gold_standard_upload_status",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "gold_standard_upload_status",
        "status",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_gold_standard_upload_status_id"),
        "gold_standard_upload_status",
        ["id"],
        unique=False,
    )
    op.alter_column(
        "history",
        "id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "history",
        "prompt_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "provider",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "scene_description",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_index("idx_16416_sqlite_autoindex_history_1", table_name="history")
    op.create_index(op.f("ix_history_id"), "history", ["id"], unique=False)
    op.alter_column(
        "prompt_tags",
        "prompt_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompt_tags",
        "tag_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "prompts",
        "topic",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "subject",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "category",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "education_level",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index("idx_16400_ix_prompts_subject", table_name="prompts")
    op.drop_index("idx_16400_ix_prompts_topic", table_name="prompts")
    op.create_index(op.f("ix_prompts_id"), "prompts", ["id"], unique=False)
    op.create_index(op.f("ix_prompts_subject"), "prompts", ["subject"], unique=False)
    op.create_index(op.f("ix_prompts_topic"), "prompts", ["topic"], unique=False)
    op.alter_column(
        "snippet_metadata",
        "id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=36),
        existing_nullable=False,
    )
    op.alter_column(
        "snippet_metadata",
        "snippet_hash",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "snippet_type",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "summary",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "embedding_text",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "html_snippet",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "filename",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "upload_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=36),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "llm_version",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "validation_status",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "retry_count",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'::bigint"),
    )
    op.alter_column(
        "snippet_metadata",
        "topic",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "key_concepts",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "education_level",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "learning_objectives",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_index(
        "idx_16428_ix_snippet_metadata_faiss_id", table_name="snippet_metadata"
    )
    op.create_index(
        op.f("ix_snippet_metadata_snippet_hash"),
        "snippet_metadata",
        ["snippet_hash"],
        unique=True,
    )
    op.create_unique_constraint(None, "snippet_metadata", ["faiss_id"])
    op.alter_column(
        "tags",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "tags",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "tags",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index("idx_16395_ix_tags_name", table_name="tags")
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.alter_column(
        "visualization_tags",
        "visualization_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "visualization_tags",
        "tag_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.add_column(
        "visualizations", sa.Column("generation_attempts", sa.Integer(), nullable=True)
    )
    op.add_column(
        "visualizations",
        sa.Column(
            "final_quality_score", sa.Numeric(precision=3, scale=1), nullable=True
        ),
    )
    op.add_column(
        "visualizations",
        sa.Column("validation_errors_count", sa.Integer(), nullable=True),
    )
    op.alter_column(
        "visualizations",
        "id",
        existing_type=sa.BIGINT(),
        server_default=None,
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "visualizations",
        "topic",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "visualizations",
        "subject",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "visualizations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "visualizations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index("idx_16408_ix_visualizations_subject", table_name="visualizations")
    op.drop_index("idx_16408_ix_visualizations_topic", table_name="visualizations")
    op.create_index(
        op.f("ix_visualizations_id"), "visualizations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_visualizations_subject"), "visualizations", ["subject"], unique=False
    )
    op.create_index(
        op.f("ix_visualizations_topic"), "visualizations", ["topic"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_visualizations_topic"), table_name="visualizations")
    op.drop_index(op.f("ix_visualizations_subject"), table_name="visualizations")
    op.drop_index(op.f("ix_visualizations_id"), table_name="visualizations")
    op.create_index(
        "idx_16408_ix_visualizations_topic", "visualizations", ["topic"], unique=False
    )
    op.create_index(
        "idx_16408_ix_visualizations_subject",
        "visualizations",
        ["subject"],
        unique=False,
    )
    op.alter_column(
        "visualizations",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "visualizations",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "visualizations",
        "subject",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "visualizations",
        "topic",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "visualizations",
        "id",
        existing_type=sa.Integer(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=9223372036854775807,
            cycle=False,
            cache=1,
        ),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("visualizations", "validation_errors_count")
    op.drop_column("visualizations", "final_quality_score")
    op.drop_column("visualizations", "generation_attempts")
    op.alter_column(
        "visualization_tags",
        "tag_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "visualization_tags",
        "visualization_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.create_index("idx_16395_ix_tags_name", "tags", ["name"], unique=True)
    op.alter_column(
        "tags",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "tags",
        "name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "tags",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_constraint(None, "snippet_metadata", type_="unique")
    op.drop_index(
        op.f("ix_snippet_metadata_snippet_hash"), table_name="snippet_metadata"
    )
    op.create_index(
        "idx_16428_ix_snippet_metadata_faiss_id",
        "snippet_metadata",
        ["faiss_id"],
        unique=True,
    )
    op.alter_column(
        "snippet_metadata",
        "learning_objectives",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "education_level",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "key_concepts",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "topic",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "retry_count",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
        existing_server_default=sa.text("'0'::bigint"),
    )
    op.alter_column(
        "snippet_metadata",
        "validation_status",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "llm_version",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "upload_id",
        existing_type=sa.String(length=36),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "filename",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "html_snippet",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "embedding_text",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "summary",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "snippet_type",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "snippet_hash",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "snippet_metadata",
        "id",
        existing_type=sa.String(length=36),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_prompts_topic"), table_name="prompts")
    op.drop_index(op.f("ix_prompts_subject"), table_name="prompts")
    op.drop_index(op.f("ix_prompts_id"), table_name="prompts")
    op.create_index("idx_16400_ix_prompts_topic", "prompts", ["topic"], unique=False)
    op.create_index(
        "idx_16400_ix_prompts_subject", "prompts", ["subject"], unique=False
    )
    op.alter_column(
        "prompts",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "education_level",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "category",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "subject",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "topic",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompts",
        "id",
        existing_type=sa.Integer(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=9223372036854775807,
            cycle=False,
            cache=1,
        ),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "prompt_tags",
        "tag_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "prompt_tags",
        "prompt_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_history_id"), table_name="history")
    op.create_index(
        "idx_16416_sqlite_autoindex_history_1", "history", ["id"], unique=True
    )
    op.alter_column(
        "history",
        "scene_description",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "provider",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "prompt_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_gold_standard_upload_status_id"),
        table_name="gold_standard_upload_status",
    )
    op.alter_column(
        "gold_standard_upload_status",
        "status",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "gold_standard_upload_status",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "gold_standard_upload_status",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "gold_standard_upload_status",
        "id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_validation_errors_severity"), table_name="validation_errors")
    op.drop_index(op.f("ix_validation_errors_phase"), table_name="validation_errors")
    op.drop_index(op.f("ix_validation_errors_id"), table_name="validation_errors")
    op.drop_index(
        op.f("ix_validation_errors_error_type"), table_name="validation_errors"
    )
    op.drop_index(
        op.f("ix_validation_errors_created_at"), table_name="validation_errors"
    )
    op.drop_table("validation_errors")
    # ### end Alembic commands ###
